{
 "title": "Processor Counter Monitor (PCM) Dashboard - cg4",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Memory Bandwidth",
   "type": "graph",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none", "label": "MByte/sec" }
   ],
   "targets": [
    {
     "expr": "rate(DRAM_Reads{socket=\"0\"}[30s])/1048576 + rate(DRAM_Writes{socket=\"0\"}[30s])/1048576 + rate(Persistent_Memory_Reads{socket=\"0\"}[30s])/1048576 + rate(Persistent_Memory_Writes{socket=\"0\"}[30s])/1048576",
     "legendFormat": "Socket0"
    },
    {
     "expr": "rate(DRAM_Reads{socket=\"1\"}[30s])/1048576 + rate(DRAM_Writes{socket=\"1\"}[30s])/1048576 + rate(Persistent_Memory_Reads{socket=\"1\"}[30s])/1048576 + rate(Persistent_Memory_Writes{socket=\"1\"}[30s])/1048576",
     "legendFormat": "Socket1"
    },
    {
     "expr": "rate(DRAM_Reads{aggregate=\"system\"}[30s])/1048576 + rate(DRAM_Writes{aggregate=\"system\"}[30s])/1048576 + rate(Persistent_Memory_Reads{aggregate=\"system\"}[30s])/1048576 + rate(Persistent_Memory_Writes{aggregate=\"system\"}[30s])/1048576",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Memory Bandwidth (MByte/sec)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(DRAM_Reads{socket=\"0\"}[30s])/1048576 + rate(DRAM_Writes{socket=\"0\"}[30s])/1048576 + rate(Persistent_Memory_Reads{socket=\"0\"}[30s])/1048576 + rate(Persistent_Memory_Writes{socket=\"0\"}[30s])/1048576",
     "legendFormat": "Socket0"
    },
    {
     "expr": "rate(DRAM_Reads{socket=\"1\"}[30s])/1048576 + rate(DRAM_Writes{socket=\"1\"}[30s])/1048576 + rate(Persistent_Memory_Reads{socket=\"1\"}[30s])/1048576 + rate(Persistent_Memory_Writes{socket=\"1\"}[30s])/1048576",
     "legendFormat": "Socket1"
    },
    {
     "expr": "rate(DRAM_Reads{aggregate=\"system\"}[30s])/1048576 + rate(DRAM_Writes{aggregate=\"system\"}[30s])/1048576 + rate(Persistent_Memory_Reads{aggregate=\"system\"}[30s])/1048576 + rate(Persistent_Memory_Writes{aggregate=\"system\"}[30s])/1048576",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Socket0 Memory Bandwidth",
   "type": "graph",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "none", "label": "MByte/sec" }
   ],
   "targets": [
    {
     "expr": "rate(DRAM_Reads{socket=\"0\"}[30s])/1048576",
     "legendFormat": "DRAM Reads"
    },
    {
     "expr": "rate(DRAM_Writes{socket=\"0\"}[30s])/1048576",
     "legendFormat": "DRAM Writes"
    },
    {
     "expr": "rate(Persistent_Memory_Reads{socket=\"0\"}[30s])/1048576",
     "legendFormat": "Persistent Memory Reads"
    },
    {
     "expr": "rate(Persistent_Memory_Writes{socket=\"0\"}[30s])/1048576",
     "legendFormat": "Persistent Memory Writes"
    }
   ]
  },
  {
   "title": "Current Socket0 Memory Bandwidth (MByte/sec)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(DRAM_Reads{socket=\"0\"}[30s])/1048576",
     "legendFormat": "DRAM Reads"
    },
    {
     "expr": "rate(DRAM_Writes{socket=\"0\"}[30s])/1048576",
     "legendFormat": "DRAM Writes"
    },
    {
     "expr": "rate(Persistent_Memory_Reads{socket=\"0\"}[30s])/1048576",
     "legendFormat": "Persistent Memory Reads"
    },
    {
     "expr": "rate(Persistent_Memory_Writes{socket=\"0\"}[30s])/1048576",
     "legendFormat": "Persistent Memory Writes"
    }
   ]
  },
  {
   "title": "Socket1 Memory Bandwidth",
   "type": "graph",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "none", "label": "MByte/sec" }
   ],
   "targets": [
    {
     "expr": "rate(DRAM_Reads{socket=\"1\"}[30s])/1048576",
     "legendFormat": "DRAM Reads"
    },
    {
     "expr": "rate(DRAM_Writes{socket=\"1\"}[30s])/1048576",
     "legendFormat": "DRAM Writes"
    },
    {
     "expr": "rate(Persistent_Memory_Reads{socket=\"1\"}[30s])/1048576",
     "legendFormat": "Persistent Memory Reads"
    },
    {
     "expr": "rate(Persistent_Memory_Writes{socket=\"1\"}[30s])/1048576",
     "legendFormat": "Persistent Memory Writes"
    }
   ]
  },
  {
   "title": "Current Socket1 Memory Bandwidth (MByte/sec)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(DRAM_Reads{socket=\"1\"}[30s])/1048576",
     "legendFormat": "DRAM Reads"
    },
    {
     "expr": "rate(DRAM_Writes{socket=\"1\"}[30s])/1048576",
     "legendFormat": "DRAM Writes"
    },
    {
     "expr": "rate(Persistent_Memory_Reads{socket=\"1\"}[30s])/1048576",
     "legendFormat": "Persistent Memory Reads"
    },
    {
     "expr": "rate(Persistent_Memory_Writes{socket=\"1\"}[30s])/1048576",
     "legendFormat": "Persistent Memory Writes"
    }
   ]
  },
  {
   "title": "Socket0 UPI Utilization Outgoing Data And Non-Data Traffic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "none", "label": "%" }
   ],
   "targets": [
    {
     "expr": "rate(Utilization_Outgoing_Data_And_Non_Data_Traffic_On_Link_0{aggregate=\"system\", socket=\"0\"}[30s])*100",
     "legendFormat": "UPI0"
    },
    {
     "expr": "rate(Utilization_Outgoing_Data_And_Non_Data_Traffic_On_Link_1{aggregate=\"system\", socket=\"0\"}[30s])*100",
     "legendFormat": "UPI1"
    },
    {
     "expr": "rate(Utilization_Outgoing_Data_And_Non_Data_Traffic_On_Link_2{aggregate=\"system\", socket=\"0\"}[30s])*100",
     "legendFormat": "UPI2"
    }
   ]
  },
  {
   "title": "Current Socket0 UPI Utilization Outgoing Data And Non-Data Traffic (%)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(Utilization_Outgoing_Data_And_Non_Data_Traffic_On_Link_0{aggregate=\"system\", socket=\"0\"}[30s])*100",
     "legendFormat": "UPI0"
    },
    {
     "expr": "rate(Utilization_Outgoing_Data_And_Non_Data_Traffic_On_Link_1{aggregate=\"system\", socket=\"0\"}[30s])*100",
     "legendFormat": "UPI1"
    },
    {
     "expr": "rate(Utilization_Outgoing_Data_And_Non_Data_Traffic_On_Link_2{aggregate=\"system\", socket=\"0\"}[30s])*100",
     "legendFormat": "UPI2"
    }
   ]
  },
  {
   "title": "Socket1 UPI Utilization Outgoing Data And Non-Data Traffic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "none", "label": "%" }
   ],
   "targets": [
    {
     "expr": "rate(Utilization_Outgoing_Data_And_Non_Data_Traffic_On_Link_0{aggregate=\"system\", socket=\"1\"}[30s])*100",
     "legendFormat": "UPI0"
    },
    {
     "expr": "rate(Utilization_Outgoing_Data_And_Non_Data_Traffic_On_Link_1{aggregate=\"system\", socket=\"1\"}[30s])*100",
     "legendFormat": "UPI1"
    },
    {
     "expr": "rate(Utilization_Outgoing_Data_And_Non_Data_Traffic_On_Link_2{aggregate=\"system\", socket=\"1\"}[30s])*100",
     "legendFormat": "UPI2"
    }
   ]
  },
  {
   "title": "Current Socket1 UPI Utilization Outgoing Data And Non-Data Traffic (%)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(Utilization_Outgoing_Data_And_Non_Data_Traffic_On_Link_0{aggregate=\"system\", socket=\"1\"}[30s])*100",
     "legendFormat": "UPI0"
    },
    {
     "expr": "rate(Utilization_Outgoing_Data_And_Non_Data_Traffic_On_Link_1{aggregate=\"system\", socket=\"1\"}[30s])*100",
     "legendFormat": "UPI1"
    },
    {
     "expr": "rate(Utilization_Outgoing_Data_And_Non_Data_Traffic_On_Link_2{aggregate=\"system\", socket=\"1\"}[30s])*100",
     "legendFormat": "UPI2"
    }
   ]
  },
  {
   "title": "Socket0 UPI Utilization Incoming Data Traffic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "none", "label": "%" }
   ],
   "targets": [
    {
     "expr": "rate(Utilization_Incoming_Data_Traffic_On_Link_0{aggregate=\"system\", socket=\"0\"}[30s])*100",
     "legendFormat": "UPI0"
    },
    {
     "expr": "rate(Utilization_Incoming_Data_Traffic_On_Link_1{aggregate=\"system\", socket=\"0\"}[30s])*100",
     "legendFormat": "UPI1"
    },
    {
     "expr": "rate(Utilization_Incoming_Data_Traffic_On_Link_2{aggregate=\"system\", socket=\"0\"}[30s])*100",
     "legendFormat": "UPI2"
    }
   ]
  },
  {
   "title": "Current Socket0 UPI Utilization Incoming Data Traffic (%)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(Utilization_Incoming_Data_Traffic_On_Link_0{aggregate=\"system\", socket=\"0\"}[30s])*100",
     "legendFormat": "UPI0"
    },
    {
     "expr": "rate(Utilization_Incoming_Data_Traffic_On_Link_1{aggregate=\"system\", socket=\"0\"}[30s])*100",
     "legendFormat": "UPI1"
    },
    {
     "expr": "rate(Utilization_Incoming_Data_Traffic_On_Link_2{aggregate=\"system\", socket=\"0\"}[30s])*100",
     "legendFormat": "UPI2"
    }
   ]
  },
  {
   "title": "Socket1 UPI Utilization Incoming Data Traffic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "none", "label": "%" }
   ],
   "targets": [
    {
     "expr": "rate(Utilization_Incoming_Data_Traffic_On_Link_0{aggregate=\"system\", socket=\"1\"}[30s])*100",
     "legendFormat": "UPI0"
    },
    {
     "expr": "rate(Utilization_Incoming_Data_Traffic_On_Link_1{aggregate=\"system\", socket=\"1\"}[30s])*100",
     "legendFormat": "UPI1"
    },
    {
     "expr": "rate(Utilization_Incoming_Data_Traffic_On_Link_2{aggregate=\"system\", socket=\"1\"}[30s])*100",
     "legendFormat": "UPI2"
    }
   ]
  },
  {
   "title": "Current Socket1 UPI Utilization Incoming Data Traffic (%)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(Utilization_Incoming_Data_Traffic_On_Link_0{aggregate=\"system\", socket=\"1\"}[30s])*100",
     "legendFormat": "UPI0"
    },
    {
     "expr": "rate(Utilization_Incoming_Data_Traffic_On_Link_1{aggregate=\"system\", socket=\"1\"}[30s])*100",
     "legendFormat": "UPI1"
    },
    {
     "expr": "rate(Utilization_Incoming_Data_Traffic_On_Link_2{aggregate=\"system\", socket=\"1\"}[30s])*100",
     "legendFormat": "UPI2"
    }
   ]
  },
  {
   "title": "Socket0 UPI Outgoing Data And Non-Data Traffic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "none", "label": "MByte/sec" }
   ],
   "targets": [
    {
     "expr": "rate(Outgoing_Data_And_Non_Data_Traffic_On_Link_0{aggregate=\"system\", socket=\"0\"}[30s])/1048576",
     "legendFormat": "UPI0"
    },
    {
     "expr": "rate(Outgoing_Data_And_Non_Data_Traffic_On_Link_1{aggregate=\"system\", socket=\"0\"}[30s])/1048576",
     "legendFormat": "UPI1"
    },
    {
     "expr": "rate(Outgoing_Data_And_Non_Data_Traffic_On_Link_2{aggregate=\"system\", socket=\"0\"}[30s])/1048576",
     "legendFormat": "UPI2"
    }
   ]
  },
  {
   "title": "Current Socket0 UPI Outgoing Data And Non-Data Traffic (MByte/sec)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(Outgoing_Data_And_Non_Data_Traffic_On_Link_0{aggregate=\"system\", socket=\"0\"}[30s])/1048576",
     "legendFormat": "UPI0"
    },
    {
     "expr": "rate(Outgoing_Data_And_Non_Data_Traffic_On_Link_1{aggregate=\"system\", socket=\"0\"}[30s])/1048576",
     "legendFormat": "UPI1"
    },
    {
     "expr": "rate(Outgoing_Data_And_Non_Data_Traffic_On_Link_2{aggregate=\"system\", socket=\"0\"}[30s])/1048576",
     "legendFormat": "UPI2"
    }
   ]
  },
  {
   "title": "Socket1 UPI Outgoing Data And Non-Data Traffic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "none", "label": "MByte/sec" }
   ],
   "targets": [
    {
     "expr": "rate(Outgoing_Data_And_Non_Data_Traffic_On_Link_0{aggregate=\"system\", socket=\"1\"}[30s])/1048576",
     "legendFormat": "UPI0"
    },
    {
     "expr": "rate(Outgoing_Data_And_Non_Data_Traffic_On_Link_1{aggregate=\"system\", socket=\"1\"}[30s])/1048576",
     "legendFormat": "UPI1"
    },
    {
     "expr": "rate(Outgoing_Data_And_Non_Data_Traffic_On_Link_2{aggregate=\"system\", socket=\"1\"}[30s])/1048576",
     "legendFormat": "UPI2"
    }
   ]
  },
  {
   "title": "Current Socket1 UPI Outgoing Data And Non-Data Traffic (MByte/sec)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(Outgoing_Data_And_Non_Data_Traffic_On_Link_0{aggregate=\"system\", socket=\"1\"}[30s])/1048576",
     "legendFormat": "UPI0"
    },
    {
     "expr": "rate(Outgoing_Data_And_Non_Data_Traffic_On_Link_1{aggregate=\"system\", socket=\"1\"}[30s])/1048576",
     "legendFormat": "UPI1"
    },
    {
     "expr": "rate(Outgoing_Data_And_Non_Data_Traffic_On_Link_2{aggregate=\"system\", socket=\"1\"}[30s])/1048576",
     "legendFormat": "UPI2"
    }
   ]
  },
  {
   "title": "Socket0 UPI Incoming Data Traffic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "none", "label": "MByte/sec" }
   ],
   "targets": [
    {
     "expr": "rate(Incoming_Data_Traffic_On_Link_0{aggregate=\"system\", socket=\"0\"}[30s])/1048576",
     "legendFormat": "UPI0"
    },
    {
     "expr": "rate(Incoming_Data_Traffic_On_Link_1{aggregate=\"system\", socket=\"0\"}[30s])/1048576",
     "legendFormat": "UPI1"
    },
    {
     "expr": "rate(Incoming_Data_Traffic_On_Link_2{aggregate=\"system\", socket=\"0\"}[30s])/1048576",
     "legendFormat": "UPI2"
    }
   ]
  },
  {
   "title": "Current Socket0 UPI Incoming Data Traffic (MByte/sec)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(Incoming_Data_Traffic_On_Link_0{aggregate=\"system\", socket=\"0\"}[30s])/1048576",
     "legendFormat": "UPI0"
    },
    {
     "expr": "rate(Incoming_Data_Traffic_On_Link_1{aggregate=\"system\", socket=\"0\"}[30s])/1048576",
     "legendFormat": "UPI1"
    },
    {
     "expr": "rate(Incoming_Data_Traffic_On_Link_2{aggregate=\"system\", socket=\"0\"}[30s])/1048576",
     "legendFormat": "UPI2"
    }
   ]
  },
  {
   "title": "Socket1 UPI Incoming Data Traffic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "none", "label": "MByte/sec" }
   ],
   "targets": [
    {
     "expr": "rate(Incoming_Data_Traffic_On_Link_0{aggregate=\"system\", socket=\"1\"}[30s])/1048576",
     "legendFormat": "UPI0"
    },
    {
     "expr": "rate(Incoming_Data_Traffic_On_Link_1{aggregate=\"system\", socket=\"1\"}[30s])/1048576",
     "legendFormat": "UPI1"
    },
    {
     "expr": "rate(Incoming_Data_Traffic_On_Link_2{aggregate=\"system\", socket=\"1\"}[30s])/1048576",
     "legendFormat": "UPI2"
    }
   ]
  },
  {
   "title": "Current Socket1 UPI Incoming Data Traffic (MByte/sec)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(Incoming_Data_Traffic_On_Link_0{aggregate=\"system\", socket=\"1\"}[30s])/1048576",
     "legendFormat": "UPI0"
    },
    {
     "expr": "rate(Incoming_Data_Traffic_On_Link_1{aggregate=\"system\", socket=\"1\"}[30s])/1048576",
     "legendFormat": "UPI1"
    },
    {
     "expr": "rate(Incoming_Data_Traffic_On_Link_2{aggregate=\"system\", socket=\"1\"}[30s])/1048576",
     "legendFormat": "UPI2"
    }
   ]
  },
  {
   "title": "Core C-state residency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "none", "label": "stacked %" }
   ],
   "targets": [
    {
     "expr": "100 * rate(RawCStateResidency{ aggregate = \"system\", index = \"0\", source = \"core\" }[30s]) / ignoring(source, index) rate(Invariant_TSC{ aggregate = \"system\" }[30s])",
     "legendFormat": "C0"
    },
    {
     "expr": "100 - (100 * rate(RawCStateResidency{ aggregate = \"system\", index = \"0\", source = \"core\" }[30s]) / ignoring(source, index) rate(Invariant_TSC{ aggregate = \"system\" }[30s]))  - (100 * rate(RawCStateResidency{ aggregate = \"system\", index = \"2\", source = \"core\" }[30s]) / ignoring(source, index) rate(Invariant_TSC{ aggregate = \"system\" }[30s]))  - (100 * rate(RawCStateResidency{ aggregate = \"system\", index = \"3\", source = \"core\" }[30s]) / ignoring(source, index) rate(Invariant_TSC{ aggregate = \"system\" }[30s]))  - (100 * rate(RawCStateResidency{ aggregate = \"system\", index = \"4\", source = \"core\" }[30s]) / ignoring(source, index) rate(Invariant_TSC{ aggregate = \"system\" }[30s]))  - (100 * rate(RawCStateResidency{ aggregate = \"system\", index = \"5\", source = \"core\" }[30s]) / ignoring(source, index) rate(Invariant_TSC{ aggregate = \"system\" }[30s]))  - (100 * rate(RawCStateResidency{ aggregate = \"system\", index = \"6\", source = \"core\" }[30s]) / ignoring(source, index) rate(Invariant_TSC{ aggregate = \"system\" }[30s]))  - (100 * rate(RawCStateResidency{ aggregate = \"system\", index = \"7\", source = \"core\" }[30s]) / ignoring(source, index) rate(Invariant_TSC{ aggregate = \"system\" }[30s]))  - (100 * rate(RawCStateResidency{ aggregate = \"system\", index = \"8\", source = \"core\" }[30s]) / ignoring(source, index) rate(Invariant_TSC{ aggregate = \"system\" }[30s]))  - (100 * rate(RawCStateResidency{ aggregate = \"system\", index = \"9\", source = \"core\" }[30s]) / ignoring(source, index) rate(Invariant_TSC{ aggregate = \"system\" }[30s]))  - (100 * rate(RawCStateResidency{ aggregate = \"system\", index = \"10\", source = \"core\" }[30s]) / ignoring(source, index) rate(Invariant_TSC{ aggregate = \"system\" }[30s])) ",
     "legendFormat": "C1"
    },
    {
     "expr": "100 * rate(RawCStateResidency{ aggregate = \"system\", index = \"2\", source = \"core\" }[30s]) / ignoring(source, index) rate(Invariant_TSC{ aggregate = \"system\" }[30s])",
     "legendFormat": "C2"
    },
    {
     "expr": "100 * rate(RawCStateResidency{ aggregate = \"system\", index = \"3\", source = \"core\" }[30s]) / ignoring(source, index) rate(Invariant_TSC{ aggregate = \"system\" }[30s])",
     "legendFormat": "C3"
    },
    {
     "expr": "100 * rate(RawCStateResidency{ aggregate = \"system\", index = \"4\", source = \"core\" }[30s]) / ignoring(source, index) rate(Invariant_TSC{ aggregate = \"system\" }[30s])",
     "legendFormat": "C4"
    },
    {
     "expr": "100 * rate(RawCStateResidency{ aggregate = \"system\", index = \"5\", source = \"core\" }[30s]) / ignoring(source, index) rate(Invariant_TSC{ aggregate = \"system\" }[30s])",
     "legendFormat": "C5"
    },
    {
     "expr": "100 * rate(RawCStateResidency{ aggregate = \"system\", index = \"6\", source = \"core\" }[30s]) / ignoring(source, index) rate(Invariant_TSC{ aggregate = \"system\" }[30s])",
     "legendFormat": "C6"
    },
    {
     "expr": "100 * rate(RawCStateResidency{ aggregate = \"system\", index = \"7\", source = \"core\" }[30s]) / ignoring(source, index) rate(Invariant_TSC{ aggregate = \"system\" }[30s])",
     "legendFormat": "C7"
    },
    {
     "expr": "100 * rate(RawCStateResidency{ aggregate = \"system\", index = \"8\", source = \"core\" }[30s]) / ignoring(source, index) rate(Invariant_TSC{ aggregate = \"system\" }[30s])",
     "legendFormat": "C8"
    },
    {
     "expr": "100 * rate(RawCStateResidency{ aggregate = \"system\", index = \"9\", source = \"core\" }[30s]) / ignoring(source, index) rate(Invariant_TSC{ aggregate = \"system\" }[30s])",
     "legendFormat": "C9"
    },
    {
     "expr": "100 * rate(RawCStateResidency{ aggregate = \"system\", index = \"10\", source = \"core\" }[30s]) / ignoring(source, index) rate(Invariant_TSC{ aggregate = \"system\" }[30s])",
     "legendFormat": "C10"
    }
   ]
  },
  {
   "title": "Current Core C-state residency (%)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * rate(RawCStateResidency{ aggregate = \"system\", index = \"0\", source = \"core\" }[30s]) / ignoring(source, index) rate(Invariant_TSC{ aggregate = \"system\" }[30s])",
     "legendFormat": "C0"
    },
    {
     "expr": "100 - (100 * rate(RawCStateResidency{ aggregate = \"system\", index = \"0\", source = \"core\" }[30s]) / ignoring(source, index) rate(Invariant_TSC{ aggregate = \"system\" }[30s]))  - (100 * rate(RawCStateResidency{ aggregate = \"system\", index = \"2\", source = \"core\" }[30s]) / ignoring(source, index) rate(Invariant_TSC{ aggregate = \"system\" }[30s]))  - (100 * rate(RawCStateResidency{ aggregate = \"system\", index = \"3\", source = \"core\" }[30s]) / ignoring(source, index) rate(Invariant_TSC{ aggregate = \"system\" }[30s]))  - (100 * rate(RawCStateResidency{ aggregate = \"system\", index = \"4\", source = \"core\" }[30s]) / ignoring(source, index) rate(Invariant_TSC{ aggregate = \"system\" }[30s]))  - (100 * rate(RawCStateResidency{ aggregate = \"system\", index = \"5\", source = \"core\" }[30s]) / ignoring(source, index) rate(Invariant_TSC{ aggregate = \"system\" }[30s]))  - (100 * rate(RawCStateResidency{ aggregate = \"system\", index = \"6\", source = \"core\" }[30s]) / ignoring(source, index) rate(Invariant_TSC{ aggregate = \"system\" }[30s]))  - (100 * rate(RawCStateResidency{ aggregate = \"system\", index = \"7\", source = \"core\" }[30s]) / ignoring(source, index) rate(Invariant_TSC{ aggregate = \"system\" }[30s]))  - (100 * rate(RawCStateResidency{ aggregate = \"system\", index = \"8\", source = \"core\" }[30s]) / ignoring(source, index) rate(Invariant_TSC{ aggregate = \"system\" }[30s]))  - (100 * rate(RawCStateResidency{ aggregate = \"system\", index = \"9\", source = \"core\" }[30s]) / ignoring(source, index) rate(Invariant_TSC{ aggregate = \"system\" }[30s]))  - (100 * rate(RawCStateResidency{ aggregate = \"system\", index = \"10\", source = \"core\" }[30s]) / ignoring(source, index) rate(Invariant_TSC{ aggregate = \"system\" }[30s])) ",
     "legendFormat": "C1"
    },
    {
     "expr": "100 * rate(RawCStateResidency{ aggregate = \"system\", index = \"2\", source = \"core\" }[30s]) / ignoring(source, index) rate(Invariant_TSC{ aggregate = \"system\" }[30s])",
     "legendFormat": "C2"
    },
    {
     "expr": "100 * rate(RawCStateResidency{ aggregate = \"system\", index = \"3\", source = \"core\" }[30s]) / ignoring(source, index) rate(Invariant_TSC{ aggregate = \"system\" }[30s])",
     "legendFormat": "C3"
    },
    {
     "expr": "100 * rate(RawCStateResidency{ aggregate = \"system\", index = \"4\", source = \"core\" }[30s]) / ignoring(source, index) rate(Invariant_TSC{ aggregate = \"system\" }[30s])",
     "legendFormat": "C4"
    },
    {
     "expr": "100 * rate(RawCStateResidency{ aggregate = \"system\", index = \"5\", source = \"core\" }[30s]) / ignoring(source, index) rate(Invariant_TSC{ aggregate = \"system\" }[30s])",
     "legendFormat": "C5"
    },
    {
     "expr": "100 * rate(RawCStateResidency{ aggregate = \"system\", index = \"6\", source = \"core\" }[30s]) / ignoring(source, index) rate(Invariant_TSC{ aggregate = \"system\" }[30s])",
     "legendFormat": "C6"
    },
    {
     "expr": "100 * rate(RawCStateResidency{ aggregate = \"system\", index = \"7\", source = \"core\" }[30s]) / ignoring(source, index) rate(Invariant_TSC{ aggregate = \"system\" }[30s])",
     "legendFormat": "C7"
    },
    {
     "expr": "100 * rate(RawCStateResidency{ aggregate = \"system\", index = \"8\", source = \"core\" }[30s]) / ignoring(source, index) rate(Invariant_TSC{ aggregate = \"system\" }[30s])",
     "legendFormat": "C8"
    },
    {
     "expr": "100 * rate(RawCStateResidency{ aggregate = \"system\", index = \"9\", source = \"core\" }[30s]) / ignoring(source, index) rate(Invariant_TSC{ aggregate = \"system\" }[30s])",
     "legendFormat": "C9"
    },
    {
     "expr": "100 * rate(RawCStateResidency{ aggregate = \"system\", index = \"10\", source = \"core\" }[30s]) / ignoring(source, index) rate(Invariant_TSC{ aggregate = \"system\" }[30s])",
     "legendFormat": "C10"
    }
   ]
  },
  {
   "title": "Package C-state residency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "none", "label": "stacked %" }
   ],
   "targets": [
    {
     "expr": "100 - (100 * rate(RawCStateResidency{ aggregate = \"system\", index = \"1\", source = \"uncore\" }[30s]) / ignoring(source, index) rate(Invariant_TSC{ aggregate = \"system\" }[30s]))  - (100 * rate(RawCStateResidency{ aggregate = \"system\", index = \"2\", source = \"uncore\" }[30s]) / ignoring(source, index) rate(Invariant_TSC{ aggregate = \"system\" }[30s]))  - (100 * rate(RawCStateResidency{ aggregate = \"system\", index = \"3\", source = \"uncore\" }[30s]) / ignoring(source, index) rate(Invariant_TSC{ aggregate = \"system\" }[30s]))  - (100 * rate(RawCStateResidency{ aggregate = \"system\", index = \"4\", source = \"uncore\" }[30s]) / ignoring(source, index) rate(Invariant_TSC{ aggregate = \"system\" }[30s]))  - (100 * rate(RawCStateResidency{ aggregate = \"system\", index = \"5\", source = \"uncore\" }[30s]) / ignoring(source, index) rate(Invariant_TSC{ aggregate = \"system\" }[30s]))  - (100 * rate(RawCStateResidency{ aggregate = \"system\", index = \"6\", source = \"uncore\" }[30s]) / ignoring(source, index) rate(Invariant_TSC{ aggregate = \"system\" }[30s]))  - (100 * rate(RawCStateResidency{ aggregate = \"system\", index = \"7\", source = \"uncore\" }[30s]) / ignoring(source, index) rate(Invariant_TSC{ aggregate = \"system\" }[30s]))  - (100 * rate(RawCStateResidency{ aggregate = \"system\", index = \"8\", source = \"uncore\" }[30s]) / ignoring(source, index) rate(Invariant_TSC{ aggregate = \"system\" }[30s]))  - (100 * rate(RawCStateResidency{ aggregate = \"system\", index = \"9\", source = \"uncore\" }[30s]) / ignoring(source, index) rate(Invariant_TSC{ aggregate = \"system\" }[30s]))  - (100 * rate(RawCStateResidency{ aggregate = \"system\", index = \"10\", source = \"uncore\" }[30s]) / ignoring(source, index) rate(Invariant_TSC{ aggregate = \"system\" }[30s])) ",
     "legendFormat": "C0"
    },
    {
     "expr": "100 * rate(RawCStateResidency{ aggregate = \"system\", index = \"1\", source = \"uncore\" }[30s]) / ignoring(source, index) rate(Invariant_TSC{ aggregate = \"system\" }[30s])",
     "legendFormat": "C1"
    },
    {
     "expr": "100 * rate(RawCStateResidency{ aggregate = \"system\", index = \"2\", source = \"uncore\" }[30s]) / ignoring(source, index) rate(Invariant_TSC{ aggregate = \"system\" }[30s])",
     "legendFormat": "C2"
    },
    {
     "expr": "100 * rate(RawCStateResidency{ aggregate = \"system\", index = \"3\", source = \"uncore\" }[30s]) / ignoring(source, index) rate(Invariant_TSC{ aggregate = \"system\" }[30s])",
     "legendFormat": "C3"
    },
    {
     "expr": "100 * rate(RawCStateResidency{ aggregate = \"system\", index = \"4\", source = \"uncore\" }[30s]) / ignoring(source, index) rate(Invariant_TSC{ aggregate = \"system\" }[30s])",
     "legendFormat": "C4"
    },
    {
     "expr": "100 * rate(RawCStateResidency{ aggregate = \"system\", index = \"5\", source = \"uncore\" }[30s]) / ignoring(source, index) rate(Invariant_TSC{ aggregate = \"system\" }[30s])",
     "legendFormat": "C5"
    },
    {
     "expr": "100 * rate(RawCStateResidency{ aggregate = \"system\", index = \"6\", source = \"uncore\" }[30s]) / ignoring(source, index) rate(Invariant_TSC{ aggregate = \"system\" }[30s])",
     "legendFormat": "C6"
    },
    {
     "expr": "100 * rate(RawCStateResidency{ aggregate = \"system\", index = \"7\", source = \"uncore\" }[30s]) / ignoring(source, index) rate(Invariant_TSC{ aggregate = \"system\" }[30s])",
     "legendFormat": "C7"
    },
    {
     "expr": "100 * rate(RawCStateResidency{ aggregate = \"system\", index = \"8\", source = \"uncore\" }[30s]) / ignoring(source, index) rate(Invariant_TSC{ aggregate = \"system\" }[30s])",
     "legendFormat": "C8"
    },
    {
     "expr": "100 * rate(RawCStateResidency{ aggregate = \"system\", index = \"9\", source = \"uncore\" }[30s]) / ignoring(source, index) rate(Invariant_TSC{ aggregate = \"system\" }[30s])",
     "legendFormat": "C9"
    },
    {
     "expr": "100 * rate(RawCStateResidency{ aggregate = \"system\", index = \"10\", source = \"uncore\" }[30s]) / ignoring(source, index) rate(Invariant_TSC{ aggregate = \"system\" }[30s])",
     "legendFormat": "C10"
    }
   ]
  },
  {
   "title": "Current Package C-state residency (%)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (100 * rate(RawCStateResidency{ aggregate = \"system\", index = \"1\", source = \"uncore\" }[30s]) / ignoring(source, index) rate(Invariant_TSC{ aggregate = \"system\" }[30s]))  - (100 * rate(RawCStateResidency{ aggregate = \"system\", index = \"2\", source = \"uncore\" }[30s]) / ignoring(source, index) rate(Invariant_TSC{ aggregate = \"system\" }[30s]))  - (100 * rate(RawCStateResidency{ aggregate = \"system\", index = \"3\", source = \"uncore\" }[30s]) / ignoring(source, index) rate(Invariant_TSC{ aggregate = \"system\" }[30s]))  - (100 * rate(RawCStateResidency{ aggregate = \"system\", index = \"4\", source = \"uncore\" }[30s]) / ignoring(source, index) rate(Invariant_TSC{ aggregate = \"system\" }[30s]))  - (100 * rate(RawCStateResidency{ aggregate = \"system\", index = \"5\", source = \"uncore\" }[30s]) / ignoring(source, index) rate(Invariant_TSC{ aggregate = \"system\" }[30s]))  - (100 * rate(RawCStateResidency{ aggregate = \"system\", index = \"6\", source = \"uncore\" }[30s]) / ignoring(source, index) rate(Invariant_TSC{ aggregate = \"system\" }[30s]))  - (100 * rate(RawCStateResidency{ aggregate = \"system\", index = \"7\", source = \"uncore\" }[30s]) / ignoring(source, index) rate(Invariant_TSC{ aggregate = \"system\" }[30s]))  - (100 * rate(RawCStateResidency{ aggregate = \"system\", index = \"8\", source = \"uncore\" }[30s]) / ignoring(source, index) rate(Invariant_TSC{ aggregate = \"system\" }[30s]))  - (100 * rate(RawCStateResidency{ aggregate = \"system\", index = \"9\", source = \"uncore\" }[30s]) / ignoring(source, index) rate(Invariant_TSC{ aggregate = \"system\" }[30s]))  - (100 * rate(RawCStateResidency{ aggregate = \"system\", index = \"10\", source = \"uncore\" }[30s]) / ignoring(source, index) rate(Invariant_TSC{ aggregate = \"system\" }[30s])) ",
     "legendFormat": "C0"
    },
    {
     "expr": "100 * rate(RawCStateResidency{ aggregate = \"system\", index = \"1\", source = \"uncore\" }[30s]) / ignoring(source, index) rate(Invariant_TSC{ aggregate = \"system\" }[30s])",
     "legendFormat": "C1"
    },
    {
     "expr": "100 * rate(RawCStateResidency{ aggregate = \"system\", index = \"2\", source = \"uncore\" }[30s]) / ignoring(source, index) rate(Invariant_TSC{ aggregate = \"system\" }[30s])",
     "legendFormat": "C2"
    },
    {
     "expr": "100 * rate(RawCStateResidency{ aggregate = \"system\", index = \"3\", source = \"uncore\" }[30s]) / ignoring(source, index) rate(Invariant_TSC{ aggregate = \"system\" }[30s])",
     "legendFormat": "C3"
    },
    {
     "expr": "100 * rate(RawCStateResidency{ aggregate = \"system\", index = \"4\", source = \"uncore\" }[30s]) / ignoring(source, index) rate(Invariant_TSC{ aggregate = \"system\" }[30s])",
     "legendFormat": "C4"
    },
    {
     "expr": "100 * rate(RawCStateResidency{ aggregate = \"system\", index = \"5\", source = \"uncore\" }[30s]) / ignoring(source, index) rate(Invariant_TSC{ aggregate = \"system\" }[30s])",
     "legendFormat": "C5"
    },
    {
     "expr": "100 * rate(RawCStateResidency{ aggregate = \"system\", index = \"6\", source = \"uncore\" }[30s]) / ignoring(source, index) rate(Invariant_TSC{ aggregate = \"system\" }[30s])",
     "legendFormat": "C6"
    },
    {
     "expr": "100 * rate(RawCStateResidency{ aggregate = \"system\", index = \"7\", source = \"uncore\" }[30s]) / ignoring(source, index) rate(Invariant_TSC{ aggregate = \"system\" }[30s])",
     "legendFormat": "C7"
    },
    {
     "expr": "100 * rate(RawCStateResidency{ aggregate = \"system\", index = \"8\", source = \"uncore\" }[30s]) / ignoring(source, index) rate(Invariant_TSC{ aggregate = \"system\" }[30s])",
     "legendFormat": "C8"
    },
    {
     "expr": "100 * rate(RawCStateResidency{ aggregate = \"system\", index = \"9\", source = \"uncore\" }[30s]) / ignoring(source, index) rate(Invariant_TSC{ aggregate = \"system\" }[30s])",
     "legendFormat": "C9"
    },
    {
     "expr": "100 * rate(RawCStateResidency{ aggregate = \"system\", index = \"10\", source = \"uncore\" }[30s]) / ignoring(source, index) rate(Invariant_TSC{ aggregate = \"system\" }[30s])",
     "legendFormat": "C10"
    }
   ]
  },
  {
   "title": "Instructions Per Cycle",
   "type": "graph",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "none", "label": "IPC" }
   ],
   "targets": [
    {
     "expr": "rate(Instructions_Retired_Any{aggregate=\"socket\", socket=\"0\"}[30s])/rate(Clock_Unhalted_Thread{aggregate=\"socket\", socket=\"0\"}[30s])",
     "legendFormat": "Socket0"
    },
    {
     "expr": "rate(Instructions_Retired_Any{aggregate=\"socket\", socket=\"1\"}[30s])/rate(Clock_Unhalted_Thread{aggregate=\"socket\", socket=\"1\"}[30s])",
     "legendFormat": "Socket1"
    },
    {
     "expr": "rate(Instructions_Retired_Any{aggregate=\"system\"}[30s])/rate(Clock_Unhalted_Thread{aggregate=\"system\"}[30s])",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Instructions Per Cycle",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(Instructions_Retired_Any{aggregate=\"socket\", socket=\"0\"}[30s])/rate(Clock_Unhalted_Thread{aggregate=\"socket\", socket=\"0\"}[30s])",
     "legendFormat": "Socket0"
    },
    {
     "expr": "rate(Instructions_Retired_Any{aggregate=\"socket\", socket=\"1\"}[30s])/rate(Clock_Unhalted_Thread{aggregate=\"socket\", socket=\"1\"}[30s])",
     "legendFormat": "Socket1"
    },
    {
     "expr": "rate(Instructions_Retired_Any{aggregate=\"system\"}[30s])/rate(Clock_Unhalted_Thread{aggregate=\"system\"}[30s])",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Active Frequency Ratio",
   "type": "graph",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "none", "label": "AFREQ" }
   ],
   "targets": [
    {
     "expr": "rate(Clock_Unhalted_Thread{aggregate=\"socket\", socket=\"0\"}[30s])/rate(Clock_Unhalted_Ref{aggregate=\"socket\", socket=\"0\"}[30s])",
     "legendFormat": "Socket0"
    },
    {
     "expr": "rate(Clock_Unhalted_Thread{aggregate=\"socket\", socket=\"1\"}[30s])/rate(Clock_Unhalted_Ref{aggregate=\"socket\", socket=\"1\"}[30s])",
     "legendFormat": "Socket1"
    },
    {
     "expr": "rate(Clock_Unhalted_Thread{aggregate=\"system\"}[30s])/rate(Clock_Unhalted_Ref{aggregate=\"system\"}[30s])",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Active Frequency Ratio",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(Clock_Unhalted_Thread{aggregate=\"socket\", socket=\"0\"}[30s])/rate(Clock_Unhalted_Ref{aggregate=\"socket\", socket=\"0\"}[30s])",
     "legendFormat": "Socket0"
    },
    {
     "expr": "rate(Clock_Unhalted_Thread{aggregate=\"socket\", socket=\"1\"}[30s])/rate(Clock_Unhalted_Ref{aggregate=\"socket\", socket=\"1\"}[30s])",
     "legendFormat": "Socket1"
    },
    {
     "expr": "rate(Clock_Unhalted_Thread{aggregate=\"system\"}[30s])/rate(Clock_Unhalted_Ref{aggregate=\"system\"}[30s])",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "L3 Cache Misses Per Instruction",
   "type": "graph",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "none", "label": "L3 MPI" }
   ],
   "targets": [
    {
     "expr": "rate(L3_Cache_Misses{aggregate=\"socket\", socket=\"0\"}[30s])/rate(Instructions_Retired_Any{aggregate=\"socket\", socket=\"0\"}[30s])",
     "legendFormat": "Socket0"
    },
    {
     "expr": "rate(L3_Cache_Misses{aggregate=\"socket\", socket=\"1\"}[30s])/rate(Instructions_Retired_Any{aggregate=\"socket\", socket=\"1\"}[30s])",
     "legendFormat": "Socket1"
    },
    {
     "expr": "rate(L3_Cache_Misses{aggregate=\"system\"}[30s])/rate(Instructions_Retired_Any{aggregate=\"system\"}[30s])",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "L3 Cache Misses Per Instruction",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(L3_Cache_Misses{aggregate=\"socket\", socket=\"0\"}[30s])/rate(Instructions_Retired_Any{aggregate=\"socket\", socket=\"0\"}[30s])",
     "legendFormat": "Socket0"
    },
    {
     "expr": "rate(L3_Cache_Misses{aggregate=\"socket\", socket=\"1\"}[30s])/rate(Instructions_Retired_Any{aggregate=\"socket\", socket=\"1\"}[30s])",
     "legendFormat": "Socket1"
    },
    {
     "expr": "rate(L3_Cache_Misses{aggregate=\"system\"}[30s])/rate(Instructions_Retired_Any{aggregate=\"system\"}[30s])",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "L2 Cache Misses Per Instruction",
   "type": "graph",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "none", "label": "L2 MPI" }
   ],
   "targets": [
    {
     "expr": "rate(L2_Cache_Misses{aggregate=\"socket\", socket=\"0\"}[30s])/rate(Instructions_Retired_Any{aggregate=\"socket\", socket=\"0\"}[30s])",
     "legendFormat": "Socket0"
    },
    {
     "expr": "rate(L2_Cache_Misses{aggregate=\"socket\", socket=\"1\"}[30s])/rate(Instructions_Retired_Any{aggregate=\"socket\", socket=\"1\"}[30s])",
     "legendFormat": "Socket1"
    },
    {
     "expr": "rate(L2_Cache_Misses{aggregate=\"system\"}[30s])/rate(Instructions_Retired_Any{aggregate=\"system\"}[30s])",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "L2 Cache Misses Per Instruction",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(L2_Cache_Misses{aggregate=\"socket\", socket=\"0\"}[30s])/rate(Instructions_Retired_Any{aggregate=\"socket\", socket=\"0\"}[30s])",
     "legendFormat": "Socket0"
    },
    {
     "expr": "rate(L2_Cache_Misses{aggregate=\"socket\", socket=\"1\"}[30s])/rate(Instructions_Retired_Any{aggregate=\"socket\", socket=\"1\"}[30s])",
     "legendFormat": "Socket1"
    },
    {
     "expr": "rate(L2_Cache_Misses{aggregate=\"system\"}[30s])/rate(Instructions_Retired_Any{aggregate=\"system\"}[30s])",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Instructions Retired Any",
   "type": "graph",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "none", "label": "Million" }
   ],
   "targets": [
    {
     "expr": "rate(Instructions_Retired_Any{aggregate=\"socket\", socket=\"0\"}[30s])/1000000",
     "legendFormat": "Socket0"
    },
    {
     "expr": "rate(Instructions_Retired_Any{aggregate=\"socket\", socket=\"1\"}[30s])/1000000",
     "legendFormat": "Socket1"
    },
    {
     "expr": "rate(Instructions_Retired_Any{aggregate=\"system\"}[30s])/1000000",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Instructions Retired Any (Million)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(Instructions_Retired_Any{aggregate=\"socket\", socket=\"0\"}[30s])/1000000",
     "legendFormat": "Socket0"
    },
    {
     "expr": "rate(Instructions_Retired_Any{aggregate=\"socket\", socket=\"1\"}[30s])/1000000",
     "legendFormat": "Socket1"
    },
    {
     "expr": "rate(Instructions_Retired_Any{aggregate=\"system\"}[30s])/1000000",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Clock Unhalted Thread",
   "type": "graph",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 94 },
   "yaxes": [
    { "format": "none", "label": "Million" }
   ],
   "targets": [
    {
     "expr": "rate(Clock_Unhalted_Thread{aggregate=\"socket\", socket=\"0\"}[30s])/1000000",
     "legendFormat": "Socket0"
    },
    {
     "expr": "rate(Clock_Unhalted_Thread{aggregate=\"socket\", socket=\"1\"}[30s])/1000000",
     "legendFormat": "Socket1"
    },
    {
     "expr": "rate(Clock_Unhalted_Thread{aggregate=\"system\"}[30s])/1000000",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Clock Unhalted Thread (Million)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(Clock_Unhalted_Thread{aggregate=\"socket\", socket=\"0\"}[30s])/1000000",
     "legendFormat": "Socket0"
    },
    {
     "expr": "rate(Clock_Unhalted_Thread{aggregate=\"socket\", socket=\"1\"}[30s])/1000000",
     "legendFormat": "Socket1"
    },
    {
     "expr": "rate(Clock_Unhalted_Thread{aggregate=\"system\"}[30s])/1000000",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "L2 Cache Hits",
   "type": "graph",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 99 },
   "yaxes": [
    { "format": "none", "label": "Million" }
   ],
   "targets": [
    {
     "expr": "rate(L2_Cache_Hits{aggregate=\"socket\", socket=\"0\"}[30s])/1000000",
     "legendFormat": "Socket0"
    },
    {
     "expr": "rate(L2_Cache_Hits{aggregate=\"socket\", socket=\"1\"}[30s])/1000000",
     "legendFormat": "Socket1"
    },
    {
     "expr": "rate(L2_Cache_Hits{aggregate=\"system\"}[30s])/1000000",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "L2 Cache Hits (Million)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(L2_Cache_Hits{aggregate=\"socket\", socket=\"0\"}[30s])/1000000",
     "legendFormat": "Socket0"
    },
    {
     "expr": "rate(L2_Cache_Hits{aggregate=\"socket\", socket=\"1\"}[30s])/1000000",
     "legendFormat": "Socket1"
    },
    {
     "expr": "rate(L2_Cache_Hits{aggregate=\"system\"}[30s])/1000000",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "L2 Cache Misses",
   "type": "graph",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 104 },
   "yaxes": [
    { "format": "none", "label": "Million" }
   ],
   "targets": [
    {
     "expr": "rate(L2_Cache_Misses{aggregate=\"socket\", socket=\"0\"}[30s])/1000000",
     "legendFormat": "Socket0"
    },
    {
     "expr": "rate(L2_Cache_Misses{aggregate=\"socket\", socket=\"1\"}[30s])/1000000",
     "legendFormat": "Socket1"
    },
    {
     "expr": "rate(L2_Cache_Misses{aggregate=\"system\"}[30s])/1000000",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "L2 Cache Misses (Million)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(L2_Cache_Misses{aggregate=\"socket\", socket=\"0\"}[30s])/1000000",
     "legendFormat": "Socket0"
    },
    {
     "expr": "rate(L2_Cache_Misses{aggregate=\"socket\", socket=\"1\"}[30s])/1000000",
     "legendFormat": "Socket1"
    },
    {
     "expr": "rate(L2_Cache_Misses{aggregate=\"system\"}[30s])/1000000",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "L3 Cache Hits",
   "type": "graph",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 109 },
   "yaxes": [
    { "format": "none", "label": "Million" }
   ],
   "targets": [
    {
     "expr": "rate(L3_Cache_Hits{aggregate=\"socket\", socket=\"0\"}[30s])/1000000",
     "legendFormat": "Socket0"
    },
    {
     "expr": "rate(L3_Cache_Hits{aggregate=\"socket\", socket=\"1\"}[30s])/1000000",
     "legendFormat": "Socket1"
    },
    {
     "expr": "rate(L3_Cache_Hits{aggregate=\"system\"}[30s])/1000000",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "L3 Cache Hits (Million)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(L3_Cache_Hits{aggregate=\"socket\", socket=\"0\"}[30s])/1000000",
     "legendFormat": "Socket0"
    },
    {
     "expr": "rate(L3_Cache_Hits{aggregate=\"socket\", socket=\"1\"}[30s])/1000000",
     "legendFormat": "Socket1"
    },
    {
     "expr": "rate(L3_Cache_Hits{aggregate=\"system\"}[30s])/1000000",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "L3 Cache Misses",
   "type": "graph",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 114 },
   "yaxes": [
    { "format": "none", "label": "Million" }
   ],
   "targets": [
    {
     "expr": "rate(L3_Cache_Misses{aggregate=\"socket\", socket=\"0\"}[30s])/1000000",
     "legendFormat": "Socket0"
    },
    {
     "expr": "rate(L3_Cache_Misses{aggregate=\"socket\", socket=\"1\"}[30s])/1000000",
     "legendFormat": "Socket1"
    },
    {
     "expr": "rate(L3_Cache_Misses{aggregate=\"system\"}[30s])/1000000",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "L3 Cache Misses (Million)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(L3_Cache_Misses{aggregate=\"socket\", socket=\"0\"}[30s])/1000000",
     "legendFormat": "Socket0"
    },
    {
     "expr": "rate(L3_Cache_Misses{aggregate=\"socket\", socket=\"1\"}[30s])/1000000",
     "legendFormat": "Socket1"
    },
    {
     "expr": "rate(L3_Cache_Misses{aggregate=\"system\"}[30s])/1000000",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Socket0 Energy Consumption",
   "type": "graph",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 119 },
   "yaxes": [
    { "format": "none", "label": "Watt" }
   ],
   "targets": [
    {
     "expr": "rate(Package_Joules_Consumed{socket=\"0\"}[30s])",
     "legendFormat": "Package Joules Consumed"
    },
    {
     "expr": "rate(DRAM_Joules_Consumed{socket=\"0\"}[30s])",
     "legendFormat": "DRAM Joules Consumed"
    }
   ]
  },
  {
   "title": "Current Socket0 Energy Consumption (Watt)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(Package_Joules_Consumed{socket=\"0\"}[30s])",
     "legendFormat": "Package Joules Consumed"
    },
    {
     "expr": "rate(DRAM_Joules_Consumed{socket=\"0\"}[30s])",
     "legendFormat": "DRAM Joules Consumed"
    }
   ]
  },
  {
   "title": "Socket1 Energy Consumption",
   "type": "graph",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 124 },
   "yaxes": [
    { "format": "none", "label": "Watt" }
   ],
   "targets": [
    {
     "expr": "rate(Package_Joules_Consumed{socket=\"1\"}[30s])",
     "legendFormat": "Package Joules Consumed"
    },
    {
     "expr": "rate(DRAM_Joules_Consumed{socket=\"1\"}[30s])",
     "legendFormat": "DRAM Joules Consumed"
    }
   ]
  },
  {
   "title": "Current Socket1 Energy Consumption (Watt)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(Package_Joules_Consumed{socket=\"1\"}[30s])",
     "legendFormat": "Package Joules Consumed"
    },
    {
     "expr": "rate(DRAM_Joules_Consumed{socket=\"1\"}[30s])",
     "legendFormat": "DRAM Joules Consumed"
    }
   ]
  }
 ]
}