{
 "title": "PMEM New",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "host",
    "label": "host",
    "query": {
     "query": "label_values(pmem_numa_tables_mb, host)"
    }
   },
   {
    "name": "tenant",
    "label": "HANA Tenant",
    "query": {
     "query": "label_values(pmem_host_memory_physical_total_mb,database_name)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "System Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "System Info",
     "type": "table",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "pmem_system_pivot_text{host=~\"$host\",database_name=~\"$tenant\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "PMEM Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "DRAM Percentage Used",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(pmem_host_memory_used_total_mb{host=~\"$host\",database_name=~\"$tenant\"}) / sum(pmem_host_memory_alloc_limit_mb{host=~\"$host\",database_name=~\"$tenant\"}) * 1000"
      }
     ]
    },
    {
     "title": "PMEM Percentage Used",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 6, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(pmem_numa_usage_percent{host=~\"$host\",database_name=~\"$tenant\"}) * 10"
      }
     ]
    },
    {
     "title": "Percentage of CS in DRAM",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 7, "x": 11, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(pmem_cs_dram_percent{host=~\"$host\",database_name=~\"$tenant\"}) "
      }
     ]
    },
    {
     "title": "PMEM to DRAM ratio",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(pmem_host_memory_used_total_mb{host=~\"$host\",database_name=~\"$tenant\"}) / sum(pmem_numa_usage_mb{host=~\"$host\",database_name=~\"$tenant\"} )   "
      }
     ]
    },
    {
     "title": "PMEM usage by Numa Node",
     "type": "bargauge",
     "description": "PMEM usage by Numa Node",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pmem_numa_usage_percent{} * 100",
       "legendFormat": "{{numa_node}}"
      }
     ]
    },
    {
     "title": "Memory Usage By Type",
     "type": "stat",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "pmem_cs_main_mb{host=~\"$host\",database_name=~\"$tenant\"} * 100"
      },
      {
       "expr": "pmem_cs_delta_mb{host=~\"$host\",database_name=~\"$tenant\"} * 100"
      },
      {
       "expr": "pmem_cs_pmem_mb{host=~\"$host\",database_name=~\"$tenant\"} * 100"
      },
      {
       "expr": "pmem_cs_nse_mb{host=~\"$host\",database_name=~\"$tenant\"} * 10"
      },
      {
       "expr": "pmem_rs_dram_mb{host=~\"$host\",database_name=~\"$tenant\"} * 10"
      }
     ]
    }
   ]
  },
  {
   "title": "PMEM Tables",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 20 tables Numa Node 0",
     "type": "table",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "pmem_numa_tables_mb{numa_node=\"0\"}"
      }
     ]
    },
    {
     "title": "Top 20 tables Numa Node 1",
     "type": "table",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "pmem_numa_tables_mb{numa_node=\"1\"}"
      }
     ]
    },
    {
     "title": "Top 20 tables Numa Node 2",
     "type": "table",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "pmem_numa_tables_mb{numa_node=\"2\"}"
      }
     ]
    },
    {
     "title": "Top 20 tables Numa Node 3",
     "type": "table",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "pmem_numa_tables_mb{numa_node=\"3\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Time Series",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "DRAM and PMEM usage",
     "type": "timeseries",
     "gridPos": { "h": 18, "w": 24, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "pmem_host_memory_alloc_limit_mb{host=~'$host',database_name=~'$tenant'}",
       "legendFormat": "DRAM Allocation Limit"
      },
      {
       "expr": "pmem_host_memory_resident_mb{host=~'$host',database_name=~'$tenant'}",
       "legendFormat": "DRAM Resident"
      },
      {
       "expr": "pmem_host_memory_used_peak_mb{host=~'$host',database_name=~'$tenant'}",
       "legendFormat": "DRAM Peak"
      },
      {
       "expr": "pmem_host_memory_used_total_mb{host=~'$host',database_name=~'$tenant'}",
       "legendFormat": "DRAM Current"
      },
      {
       "expr": "sum(pmem_numa_usage_total_mb{host=~'$host',database_name=~'$tenant'})",
       "legendFormat": "PMEM  Available"
      },
      {
       "expr": "sum(pmem_numa_usage_mb{host=~'$host',database_name=~'$tenant'})",
       "legendFormat": "PMEM  Current"
      }
     ]
    }
   ]
  },
  {
   "title": "Host Services Time Series",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory and Disk",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "pmem_host_services_history_memory_mb{host=~'$host',database_name=~'$tenant'}",
       "legendFormat": "Memory Usage"
      },
      {
       "expr": "pmem_host_services_history_disk_mb{host=~'$host',database_name=~'$tenant'}",
       "legendFormat": "Disk  Usage"
      }
     ]
    },
    {
     "title": "CPU",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "pmem_host_services_history_cpu_percent{host=~'$host',database_name=~'$tenant'}",
       "legendFormat": "CPU Usage"
      },
      {
       "expr": "pmem_host_services_history_system_cpu_percent{host=~'$host',database_name=~'$tenant'}",
       "legendFormat": "System CPU  Usage"
      }
     ]
    },
    {
     "title": "Transactions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "pmem_host_services_history_transactions_count{host=~'$host',database_name=~'$tenant'}",
       "legendFormat": "Active Transactions"
      },
      {
       "expr": "pmem_host_services_history_threads_count{host=~'$host',database_name=~'$tenant'}",
       "legendFormat": "Active Threads"
      },
      {
       "expr": "pmem_host_services_history_sql_executions_count{host=~'$host',database_name=~'$tenant'}",
       "legendFormat": "Active SQL"
      }
     ]
    }
   ]
  },
  {
   "title": "Debug",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Query Execution Time",
     "type": "table",
     "gridPos": { "h": 50, "w": 24, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "debug_min_cursor_secs{host=~'$host',database_name=~'$tenant'}"
      },
      {
       "expr": "debug_avg_cursor_secs{host=~'$host',database_name=~'$tenant'}"
      },
      {
       "expr": "debug_max_cursor_secs{host=~'$host',database_name=~'$tenant'}"
      },
      {
       "expr": "debug_records_count{host=~'$host',database_name=~'$tenant'}"
      }
     ]
    }
   ]
  }
 ]
}